config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :recipes, only: [:index, :show, :destroy]
    resources :searches, only: [:index]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/customers#guest_sign_in"
  end

  scope module: :public do
    root to: "recipes#top"
    get "customers/unsubscribe"
    patch "customers/withdraw"
    get "favorites" => "favorites#index"
    get "reviews" => "reviews#index"
    get "search_tag" => "searches#search_tag"
    resources :customers, only: [:show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy]
      get "follows" => "relationships#follows"
      get "followers" => "relationships#followers"
    end
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resources :foods, only: [:new, :create, :destroy, :index]
      resources :procedures, only: [:new, :create, :destroy, :index]
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index]
    resources :view_counts, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new, :create, :index]
    resources :news, only: [:index]
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews = Review.page(params[:page]).per(10)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to request.referer
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>投稿者</th>
          <th>評価</th>
          <th>コメント</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% reviews.each do |review| %>
        <tr>
          <td><%= link_to review.customer.name, admin_customer_path(review.customer), class: "text-dark" %></td>
          <td>
            <div class="mb-4" id="star-rate<%= review.id %>"></div>
              <script>
                $("#star-rate<%= review.id %>").empty();
                $("#star-rate<%= review.id %>").raty({
                size      : 36,
                starOff   : "<%= asset_path("star-off.png") %>",
                starOn    : "<%= asset_path("star-on.png") %>",
                half      : false,
                readOnly: true,
                score: <%= review.star %>,
              });
              </script>
          </td>
          <td><%= review.comment %></td>
          <td><%= link_to "削除", admin_review_path(review), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-danger btn-{themecolor} rounded-pill" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= paginate reviews %>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-12">
      <h4 class="text-center">レビュー一覧</h4>
    </div>
  </div>
  <%= render "index", reviews: @reviews %>
</div>