config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :recipes, only: [:index, :show, :destroy]
    resources :searches, only: [:index]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/customers#guest_sign_in"
  end

  scope module: :public do
    root to: "recipes#top"
    get "customers/unsubscribe"
    patch "customers/withdraw"
    get "favorites" => "favorites#index"
    get "reviews" => "reviews#index"
    get "search_tag" => "searches#search_tag"
    resources :customers, only: [:show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy]
      get "follows" => "relationships#follows"
      get "followers" => "relationships#followers"
    end
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resources :foods, only: [:new, :create, :destroy, :index]
      resources :procedures, only: [:new, :create, :destroy, :index]
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index]
    resources :view_counts, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new, :create, :index]
    resources :news, only: [:index]
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @range = params[:range]
    if @range == "customer"
      @customers = Customer.looks(params[:search], params[:word]).page(params[:page]).per(10)
    elsif @range == "recipe"
      @recipes = Recipe.looks(params[:search], params[:word]).page(params[:page])
    else
      @reviews = Review.looks(params[:search], params[:word]).page(params[:page]).per(10)
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search.html.erb
<% if admin_signed_in? %>
  <div class="mt-3 ml-3">
    <%= form_with url: admin_searches_path, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["会員", "customer"], ["レシピ", "recipe"], ["レビュー", "review"]]) %>
      <%= f.select :search, options_for_select([["完全一致", "perfect_match"], ["前方一致", "forward_match"],  ["後方一致", "backword_match"], ["部分一致", "partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-warning btn-{themecolor} rounded-pill" %>
    <% end %>
  </div>
<% end %>

app/views/admin/searches/index.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-12">
      <h4 class="text-center">「<%= params[:word] %>」の検索結果</h4>
    </div>
  </div>
  <% if @range == "customer" %>
    <%= render "admin/customers/index", customers: @customers %>
  <% elsif @range == "recipe" %>
    <%= render "public/recipes/index", recipes: @recipes %>
  <% else %>
    <%= render "admin/reviews/index", reviews: @reviews %>
  <% end %>
</div>