config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :recipes, only: [:index, :show, :destroy]
    resources :searches, only: [:index]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/customers#guest_sign_in"
  end

  scope module: :public do
    root to: "recipes#top"
    get "customers/unsubscribe"
    patch "customers/withdraw"
    get "favorites" => "favorites#index"
    get "reviews" => "reviews#index"
    get "search_tag" => "searches#search_tag"
    resources :customers, only: [:show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy]
      get "follows" => "relationships#follows"
      get "followers" => "relationships#followers"
    end
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resources :foods, only: [:new, :create, :destroy, :index]
      resources :procedures, only: [:new, :create, :destroy, :index]
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index]
    resources :view_counts, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new, :create, :index]
    resources :news, only: [:index]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @category = Category.new
    @categories = Category.page(params[:page]).per(10)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      @categories = Category.page(params[:page]).per(10)
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end


  private


  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <%= render "layouts/error", object: @category %>
  <div class="row">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-8 offset-2">
      <h4 class="text-center my-5">カテゴリー編集</h4>
      <%= form_with model: @category, url: admin_category_path do |f| %>
        <div class="form-group mb-4">
          <%= f.text_field :name, placeholder: "カテゴリー名(20文字以内)", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-warning btn-block btn-{themecolor} rounded-pill" %>
        </div>
      <% end %>
    </div>
    <div class="offset-lg-4 offset-md-3 offset-sm-2 offset-2"></div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <%= render "layouts/error", object: @category %>
  <div class="row">
    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 col-8 offset-2">
      <h4 class="text-center my-5">カテゴリー追加</h4>
      <%= form_with model: @category, url: admin_categories_path do |f| %>
        <div class="form-group mb-4">
          <%= f.text_field :name, autofocus: true, placeholder: "カテゴリー名(20文字以内)", class: "form-control" %>
        </div>

        <div class="form-group mb-5">
          <%= f.submit "新規登録", class: "btn btn-warning btn-block btn-{themecolor} rounded-pill" %>
        </div>
      <% end %>
      <h4 class="text-center mb-4">カテゴリー一覧</h4>
      <% @categories.each do |category| %>
        <div class="mb-3 category-menu">
          <p><strong><%= category.name %></strong></p>
          <p><%= link_to "編集", edit_admin_category_path(category), class: "btn btn-warning btn-{themecolor} rounded-pill" %></p>
          <p><%= link_to "削除", admin_category_path(category), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-danger btn-{themecolor} rounded-pill" %></p>
        </div>
      <% end %>
    </div>
    <div class="offset-lg-4 offset-md-3 offset-sm-2 offset-2"></div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @categories %>
    </div>
  </div>
</div>