config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :recipes, only: [:index, :show, :destroy]
    resources :searches, only: [:index]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/customers#guest_sign_in"
  end

  scope module: :public do
    root to: "recipes#top"
    get "customers/unsubscribe"
    patch "customers/withdraw"
    get "favorites" => "favorites#index"
    get "reviews" => "reviews#index"
    get "search_tag" => "searches#search_tag"
    resources :customers, only: [:show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy]
      get "follows" => "relationships#follows"
      get "followers" => "relationships#followers"
    end
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resources :foods, only: [:new, :create, :destroy, :index]
      resources :procedures, only: [:new, :create, :destroy, :index]
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index]
    resources :view_counts, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new, :create, :index]
    resources :news, only: [:index]
  end
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <a class="navbar-brand" href="/admin/customers"><strong>Bodymake Kitchen管理者サイト</strong><i class="fas fa-dumbbell"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if admin_signed_in? %>
      <li class="nav-item active">
        <%= link_to admin_customers_path, class: "nav-link" do %>
          <i class="fas fa-user"></i> <strong>会員管理</strong>
        <% end %>
      <li class="nav-item active">
        <%= link_to admin_recipes_path, class: "nav-link" do %>
          <i class="fas fa-utensils"></i> <strong>レシピ管理</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to admin_reviews_path, class: "nav-link" do %>
          <i class="fas fa-star"></i> <strong>レビュー管理</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to admin_categories_path, class: "nav-link" do %>
          <i class="fas fa-book-open"></i> <strong>カテゴリー管理</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
          <i class="fas fa-sign-out-alt"></i> <strong>ログアウト</strong>
        <% end %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-home"></i> <strong>TOP</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to new_admin_session_path, class: "nav-link" do %>
          <i class="fas fa-sign-in-alt"></i> <strong>ログイン</strong>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
<div class="row">
  <div class="col-md-12">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h5 class="alert-heading"><%= object.errors.count %>件のエラーが発生しました</h5>
      <hr>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_public_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <a class="navbar-brand" href="/"><strong>Bodymake Kitchen</strong><i class="fas fa-dumbbell"></i></a>
  <% if customer_signed_in? %>
    <span class="navbar-text text-dark">
      ようこそ <strong><%= current_customer.name %></strong> さん
    </span>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if customer_signed_in? %>
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-home"></i> <strong>TOP</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to customer_path(current_customer), class: "nav-link" do %>
          <i class="fas fa-user"></i> <strong>マイページ</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to new_recipe_path, class: "nav-link" do %>
          <i class="fas fa-utensils"></i> <strong>レシピ投稿</strong>
        <% end %>
      </li>
      <% if unchecked_notifications.any? %>
        <li class="nav-item active">
          <%= link_to notifications_path, class: "nav-link", style: "color: tomato;" do %>
            <i class="fas fa-bell"></i> <strong>通知</strong>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to notifications_path, class: "nav-link" do %>
            <i class="fas fa-check"></i> <strong>通知</strong>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to new_contact_path, class: "nav-link" do %>
          <i class="fas fa-envelope"></i> <strong>お問い合わせ</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link" do %>
          <i class="fas fa-sign-out-alt"></i> <strong>ログアウト</strong>
        <% end %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to customers_guest_sign_in_path, method: :post, class: "nav-link" do %>
          <i class="fas fa-user-circle"></i> <strong>ゲストログイン</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to new_customer_session_path, class: "nav-link" do %>
          <i class="fas fa-sign-in-alt"></i> <strong>ログイン</strong>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to new_customer_registration_path, class: "nav-link" do %>
          <i class="fas fa-user"></i> <strong>ユーザー登録(無料)</strong>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodymakeKitchen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <% if request.fullpath.include? "admin"  %>
        <%= render "layouts/admin_header" %>
      <% else%>
        <%= render "layouts/public_header" %>
      <% end %>
    </header>
    <main>
      <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <h5><%= notice %></h5>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
      <% if request.fullpath.include? "admin"  %>
        <%= render "admin/searches/search" %>
      <% end %>
    </main>
    <%= yield %>
  </body>
</html>